# Generated by Django 5.2.9 on 2026-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_updated_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending_shipment', 'Pending Shipment'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed')], default='created', max_length=20),
        ),
    ]
