# Generated by Django 5.2.9 on 2026-03-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending_shipment', 'Pending Shipment'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed')], db_index=True, default='created', max_length=20),
        ),
    ]
